# Generated by Django 5.1.6 on 2026-02-24 08:29

import api.utils
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_type', models.CharField(max_length=255)),
                ('stakeholder_title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disable', 'Disable')], default='active', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.division')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.province')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_starting_date', models.DateField(blank=True, null=True)),
                ('project_reference_no', models.CharField(blank=True, max_length=200, null=True)),
                ('total_budget_allocated', models.CharField(blank=True, max_length=200, null=True)),
                ('budget_utilized', models.CharField(blank=True, max_length=200, null=True)),
                ('budget_variance', models.CharField(blank=True, max_length=200, null=True)),
                ('budget_remaining', models.CharField(blank=True, max_length=200, null=True)),
                ('xer_file', models.FileField(blank=True, null=True, upload_to=api.utils.project_doc_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xer'])])),
                ('boundary_file', models.FileField(blank=True, null=True, upload_to=api.utils.project_doc_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson', 'json'])])),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.district')),
                ('division', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.division')),
                ('province', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.province')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='api.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='PictorialArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.utils.project_image_file_path)),
                ('image_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictorial_archive', to='api.project')),
            ],
            options={
                'ordering': ['-image_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='division',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='api.province'),
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('companyLogo', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.stakeholder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tehsil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehsil_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tehsils', to='api.district')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tehsils', to='api.division')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tehsils', to='api.province')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tehsil',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tehsil'),
        ),
    ]
