# Generated by Django 5.1.6 on 2026-02-26 07:21

import api.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='boundary_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=api.utils.project_doc_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['geojson', 'json'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='xer_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=api.utils.project_doc_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xer'])]),
        ),
    ]
