# Generated by Django 6.0.2 on 2026-04-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tehsil',
            name='division',
        ),
        migrations.RemoveField(
            model_name='district',
            name='division',
        ),
        migrations.AddField(
            model_name='district',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.zone'),
        ),
        migrations.AddField(
            model_name='tehsil',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tehsils', to='api.zone'),
        ),
        migrations.AlterField(
            model_name='tehsil',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tehsils', to='api.district'),
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_name', models.CharField(max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to='api.zone')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.circle'),
        ),
        migrations.AddField(
            model_name='tehsil',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tehsils', to='api.circle'),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
