# Generated by Django 6.0.2 on 2026-04-25 11:08

import api.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tehsil_division_remove_district_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_starting_date', models.DateField(blank=True, null=True)),
                ('project_reference_no', models.CharField(blank=True, max_length=200, null=True)),
                ('total_budget', models.CharField(blank=True, max_length=200, null=True)),
                ('total_consume', models.CharField(blank=True, max_length=200, null=True)),
                ('remaining_budget', models.CharField(blank=True, max_length=200, null=True)),
                ('xer_file', models.FileField(blank=True, max_length=500, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xer'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.district')),
                ('stakeholder', models.ManyToManyField(blank=True, related_name='projects', to='api.stakeholder')),
                ('tehsil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tehsil')),
                ('zone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('progress', models.FloatField(default=0)),
                ('progress_date', models.DateField(blank=True, null=True)),
                ('progress_status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('task_type', models.CharField(default='task', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.projectactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.project')),
            ],
            options={
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='ProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.utils.project_image_file_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('image_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.projectactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDelayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_start_date', models.DateField()),
                ('delay_end_date', models.DateField()),
                ('delay_days', models.IntegerField(default=0)),
                ('originator', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.stakeholder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_logs', to='api.project')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_logs', to='api.projectactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='project_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx'])])),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.projectactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='api.projectactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='api.projectactivity')),
            ],
        ),
    ]
