# Generated by Django 6.0.1 on 2026-02-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_admin_myuser_is_staff_myuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('contractor', 'Contractor'), ('consultant', 'Consultant')], default='contractor', max_length=20),
        ),
    ]
