# Generated by Django 5.1.6 on 2026-03-02 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_admin_myuser_is_staff_myuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('contractor', 'Contractor'), ('consultant', 'Consultant')], default='contractor', max_length=20),
        ),
        migrations.RemoveField(
            model_name='project',
            name='stakeholder',
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=100)),
                ('activity_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('percent_complete', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='stakeholder',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.stakeholder'),
        ),
    ]
