# Generated by Django 6.0.2 on 2026-03-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_myuser_role'),
        ('api', '0004_alter_myuser_role_remove_project_stakeholder_and_more'),
    ]

    operations = [
    ]
