# Generated by Django 5.1.6 on 2026-03-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_myuser_role'),
        ('api', '0004_alter_myuser_role_remove_project_stakeholder_and_more'),
    ]

    operations = [
    ]
