# Generated by Django 5.1.6 on 2026-03-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userpermission_created_by_userpermission_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='sub_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
