# Generated by Django 5.1.6 on 2026-03-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userpermission_sub_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'sidebar_label', 'sub_label')},
        ),
    ]
