# Generated by Django 6.0.2 on 2026-03-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20260303_1242'),
        ('api', '0009_alter_userpermission_unique_together'),
    ]

    operations = [
    ]
