# Generated by Django 6.0.2 on 2026-03-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userpermission_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectactivity',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='projectactivity',
            old_name='percent_complete',
            new_name='progress',
        ),
        migrations.RemoveField(
            model_name='projectactivity',
            name='finish_date',
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='activity_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='activity_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
