# Generated by Django 6.0.2 on 2026-03-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_projectactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.projectactivity'),
        ),
    ]
