# Generated by Django 6.0.2 on 2026-03-10 (merge)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_projectactivity_options_and_more'),
        ('api', '0010_merge_20260305_1003'),
    ]

    operations = [
    ]
