# Generated by Django 6.0.2 on 2026-03-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20260310_merge'),
        ('api', '0011_projectactivity_parent'),
    ]

    operations = [
    ]
