# Generated by Django 6.0.2 on 2026-03-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260311_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectactivity',
            options={'ordering': ['parent_id', 'start_date']},
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='task_type',
            field=models.CharField(default='task', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='api.projectactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successors', to='api.projectactivity')),
            ],
        ),
    ]
