# Generated by Django 6.0.2 on 2026-03-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_projectactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='actual_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='actual_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
