# Generated by Django 6.0.2 on 2026-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_projectactivity_actual_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='xer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
