# Generated by Django 6.0.2 on 2026-03-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_projectactivity_xer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectactivity',
            name='xer_id',
        ),
    ]
