# Generated by Django 6.0.2 on 2026-03-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_projectactivity_xer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectactivity',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='project',
            name='boundary_file',
        ),
    ]
