# Generated by Django 6.0.2 on 2026-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_projectactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allocation_capital_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='allocation_revenue_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='allocation_total_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pd_release_capital_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pd_release_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pd_release_total_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='percentage_utilization_capital',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='percentage_utilization_revenue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='percentage_utilization_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pifra_utilization_capital_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pifra_utilization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pifra_utilization_revenue_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pifra_utilization_total_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spending_release_capital_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spending_release_revenue_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='spending_release_total_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
