# Generated by Django 6.0.2 on 2026-04-01 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_project_allocation_capital_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDelayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_start_date', models.DateField()),
                ('delay_end_date', models.DateField()),
                ('delay_days', models.IntegerField(default=0)),
                ('originator', models.CharField(max_length=100)),
                ('action_by', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('recommended_action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_logs', to='api.projectactivity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_logs', to='api.project')),
            ],
        ),
    ]
