# Generated by Django 6.0.2 on 2026-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_activitydelaylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydelaylog',
            name='originator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
