# Generated by Django 6.0.2 on 2026-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_activitydelaylog_originator'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='progress_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
