# Generated by Django 6.0.2 on 2026-04-06 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_projectactivity_progress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydelaylog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitydelaylog',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.stakeholder'),
        ),
        migrations.AlterField(
            model_name='activitydelaylog',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitydelaylog',
            name='recommended_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
