# Generated by Django 6.0.2 on 2026-04-07 06:20

import api.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_activitydelaylog_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.utils.project_image_file_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('image_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.projectactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
            ],
        ),
    ]
