# Generated by Django 6.0.2 on 2026-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_progressimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='progress_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
    ]
