# Generated by Django 6.0.2 on 2026-04-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_projectdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='file',
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
