# Generated by Django 6.0.2 on 2026-04-09 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_projectdocument_file_projectdocument_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='file_url',
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='project_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx'])]),
        ),
    ]
